// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

/*
Package consignment is a generated protocol buffer package.

It is generated from these files:
	proto/consignment/consignment.proto

It has these top-level messages:
	Manifest
	Container
	GetRequest
	Response
*/
package consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Manifest struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight      int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers  []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	VesselId    string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId" json:"vessel_id,omitempty"`
}

func (m *Manifest) Reset()                    { *m = Manifest{} }
func (m *Manifest) String() string            { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()               {}
func (*Manifest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Manifest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Manifest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Manifest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Manifest) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Manifest) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	Origin     string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	UserId     string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
	Created   bool        `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Manifest  *Manifest   `protobuf:"bytes,2,opt,name=manifest" json:"manifest,omitempty"`
	Manifests []*Manifest `protobuf:"bytes,3,rep,name=manifests" json:"manifests,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetManifest() *Manifest {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *Response) GetManifests() []*Manifest {
	if m != nil {
		return m.Manifests
	}
	return nil
}

func init() {
	proto.RegisterType((*Manifest)(nil), "consignment.Manifest")
	proto.RegisterType((*Container)(nil), "consignment.Container")
	proto.RegisterType((*GetRequest)(nil), "consignment.GetRequest")
	proto.RegisterType((*Response)(nil), "consignment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Consignment service

type ConsignmentClient interface {
	Create(ctx context.Context, in *Manifest, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type consignmentClient struct {
	c           client.Client
	serviceName string
}

func NewConsignmentClient(serviceName string, c client.Client) ConsignmentClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "consignment"
	}
	return &consignmentClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *consignmentClient) Create(ctx context.Context, in *Manifest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Consignment.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Consignment.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Consignment service

type ConsignmentHandler interface {
	Create(context.Context, *Manifest, *Response) error
	Get(context.Context, *GetRequest, *Response) error
}

func RegisterConsignmentHandler(s server.Server, hdlr ConsignmentHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Consignment{hdlr}, opts...))
}

type Consignment struct {
	ConsignmentHandler
}

func (h *Consignment) Create(ctx context.Context, in *Manifest, out *Response) error {
	return h.ConsignmentHandler.Create(ctx, in, out)
}

func (h *Consignment) Get(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ConsignmentHandler.Get(ctx, in, out)
}

func init() { proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0x2d, 0xe5, 0xa3, 0x9d, 0x1a, 0x0f, 0x93, 0x08, 0x1b, 0x3d, 0xd8, 0xd4, 0x0b, 0x27,
	0x8c, 0x90, 0xa8, 0x77, 0x0e, 0x84, 0x83, 0x97, 0x7d, 0x01, 0x83, 0xdd, 0x11, 0x37, 0xb1, 0xbb,
	0xd8, 0x59, 0xf4, 0xea, 0x03, 0xf8, 0x22, 0xbe, 0xa5, 0x61, 0x4b, 0xa1, 0x44, 0xb9, 0xed, 0xfc,
	0x3f, 0xd2, 0xdf, 0x4c, 0x0a, 0xd7, 0xab, 0xd2, 0x3a, 0x7b, 0x93, 0x5b, 0xc3, 0x7a, 0x69, 0x0a,
	0x32, 0xae, 0xf9, 0x1e, 0x79, 0x17, 0x93, 0x86, 0x94, 0xfd, 0x04, 0x10, 0x3d, 0x2e, 0x8c, 0x7e,
	0x21, 0x76, 0x78, 0x06, 0x2d, 0xad, 0x44, 0x90, 0x06, 0xc3, 0x58, 0xb6, 0xb4, 0xc2, 0x14, 0x12,
	0x45, 0x9c, 0x97, 0x7a, 0xe5, 0xb4, 0x35, 0xa2, 0xe5, 0x8d, 0xa6, 0x84, 0x7d, 0xe8, 0x7e, 0x92,
	0x5e, 0xbe, 0x3a, 0x11, 0xa6, 0xc1, 0xb0, 0x23, 0xb7, 0x13, 0xde, 0x01, 0xe4, 0xd6, 0xb8, 0x85,
	0x36, 0x54, 0xb2, 0x68, 0xa7, 0xe1, 0x30, 0x19, 0xf7, 0x47, 0x4d, 0x96, 0x69, 0x6d, 0xcb, 0x46,
	0x12, 0x2f, 0x21, 0xfe, 0x20, 0x66, 0x7a, 0x7b, 0xd2, 0x4a, 0x74, 0xfc, 0xf7, 0xa2, 0x4a, 0x98,
	0xab, 0xac, 0x80, 0x78, 0xd7, 0xfa, 0xc3, 0x7a, 0x05, 0x49, 0xbe, 0x66, 0x67, 0x0b, 0x2a, 0x37,
	0xdd, 0x8a, 0x15, 0x6a, 0x69, 0xae, 0x36, 0xa8, 0xb6, 0xd4, 0x4b, 0x6d, 0x3c, 0x6a, 0x2c, 0xb7,
	0x13, 0x0e, 0xa0, 0xb7, 0xe6, 0xaa, 0xd4, 0xae, 0x8c, 0xcd, 0x38, 0x57, 0xd9, 0x29, 0xc0, 0x8c,
	0x9c, 0xa4, 0xf7, 0x35, 0xb1, 0xcb, 0xbe, 0x03, 0x88, 0x24, 0xf1, 0xca, 0x1a, 0x26, 0x14, 0xd0,
	0xcb, 0x4b, 0x5a, 0x38, 0xaa, 0x08, 0x22, 0x59, 0x8f, 0x78, 0x0b, 0x51, 0xb1, 0x3d, 0xa7, 0x67,
	0x48, 0xc6, 0xe7, 0x07, 0x6b, 0xd7, 0xb7, 0x96, 0xbb, 0x18, 0x4e, 0x20, 0xae, 0xdf, 0x2c, 0x42,
	0x7f, 0xaa, 0x23, 0x9d, 0x7d, 0x6e, 0xfc, 0x15, 0x40, 0x32, 0xdd, 0x67, 0xf0, 0x01, 0xba, 0x53,
	0x8f, 0x80, 0xff, 0x77, 0x2f, 0x0e, 0xe5, 0x7a, 0x93, 0xec, 0x04, 0xef, 0x21, 0x9c, 0x91, 0xc3,
	0xc1, 0x81, 0xbf, 0x5f, 0xfc, 0x68, 0xf1, 0xb9, 0xeb, 0x7f, 0xa7, 0xc9, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x32, 0x02, 0xb0, 0x75, 0x02, 0x00, 0x00,
}
